# -*- coding: utf-8 -*-
"""multi-pdf-rag-assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cNtSMRPMG-_r_PGEyK37nkjkCCWvQkTA
"""

!pip install -q langchain langchain-community chromadb sentence-transformers gradio pypdf langchain-text-splitters langchain_google_genai

from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import Chroma
from langchain_classic.chains import RetrievalQA

from langchain_community.llms import HuggingFacePipeline
import gradio as gr
import glob

docs = []

for file in glob.glob("/content/drive/MyDrive/project 1/*.pdf"):
    loader = PyPDFLoader(file)
    docs.extend(loader.load())

print(f"Loaded {len(docs)} pages")

text_splitter=RecursiveCharacterTextSplitter(chunk_size=1000,chunk_overlap=400,separators=["\n\n", "\n", ".", " "])

texts=text_splitter.split_documents(docs)

len(texts)

embedding=HuggingFaceEmbeddings(model_name="sentence-transformers/all-mpnet-base-v2")

import shutil
import os

# Remove the existing chroma_db directory to ensure a fresh start with the correct embedding dimension
if os.path.exists("chroma_db"):
    print("Removing existing chroma_db directory...")
    shutil.rmtree("chroma_db")
else:
    print("chroma_db directory does not exist. Creating a new one.")

vectordb = Chroma.from_documents(
    documents=texts,
    embedding=embedding,
    persist_directory="chroma_db"
)

vectordb.persist()
print("Chroma DB created and persisted.")

vectordb

#retriever = vectordb.as_retriever(
    #search_type="similarity",
    #search_kwargs={"k": 3}
#)

retriever = vectordb.as_retriever(
    search_type="mmr",
    search_kwargs={
        "k": 8,
        "fetch_k": 20
    }
)

from langchain_classic.chains import RetrievalQA
from langchain_google_genai import ChatGoogleGenerativeAI
from google.colab import userdata

# Retrieve the API key from Colab Secrets named 'project1'
GOOGLE_API_KEY = userdata.get('project1')

llm = ChatGoogleGenerativeAI(model="gemini-2.5-flash", google_api_key=GOOGLE_API_KEY)

qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=retriever,
    chain_type="stuff",
    return_source_documents=True
)

query = "Compare AWS Well-Architected and Azure security guidance?"
result = qa_chain.invoke({"query": query})

print(result["result"])

result
